export const ERROR_CODES = {
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',

  VALIDATION_ERROR: 'VALIDATION_ERROR',

  UNAUTHORIZED: 'UNAUTHORIZED',

  FORBIDDEN: 'FORBIDDEN',

  NOT_FOUND: 'NOT_FOUND',

  CONFLICT: 'CONFLICT',

  RATE_LIMITED: 'RATE_LIMITED',

  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',

  USER_NOT_FOUND: 'USER_NOT_FOUND',

  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',

  INVALID_TOKEN: 'INVALID_TOKEN',

  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
